# Generated by Django 4.1.6 on 2023-02-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50, verbose_name='Nome do Pet')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone:')),
                ('data', models.DateField(verbose_name='Data da reserva')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
        ),
    ]
