# Generated by Django 4.1.6 on 2023-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva de Banho', 'verbose_name_plural': 'Reservas de Banho'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='nome',
            field=models.CharField(default='sem nome', max_length=50, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tamanho',
            field=models.IntegerField(choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], null=True, verbose_name='Tamanho'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='turno',
            field=models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde')], default='não especificado', max_length=10, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(help_text='dd/mm/aaaa', verbose_name='Data da reserva'),
        ),
    ]
