# Generated by Django 4.1.6 on 2023-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_alter_reserva_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tamanho',
            field=models.IntegerField(choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], default=1, verbose_name='Tamanho'),
        ),
    ]
