# Generated by Django 4.1.6 on 2023-02-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_alter_reserva_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tamanho',
        ),
    ]
