# Generated by Django 4.1.6 on 2023-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_petshop_reserva_petshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pet',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('coelho', 'Coelho')], max_length=14, null=True, verbose_name='Pet'),
        ),
    ]
