# Generated by Django 4.1.6 on 2023-03-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_pet_alter_reserva_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.pet'),
        ),
    ]
