# Generated by Django 4.1.6 on 2023-03-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0013_alter_reserva_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pet',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Pet'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
