# Generated by Django 4.1.6 on 2023-03-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0014_alter_reserva_pet_delete_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pet',
            field=models.CharField(blank=True, choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('coelho', 'Coelho')], max_length=15, null=True, verbose_name='Pet'),
        ),
    ]
