# Generated by Django 4.1.6 on 2023-03-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0015_alter_reserva_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=15, verbose_name='Pet')),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pet',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.pet'),
        ),
    ]
