# Generated by Django 4.1.6 on 2023-03-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0016_pet_alter_reserva_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pet',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
