# Generated by Django 4.1.6 on 2023-02-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reserva_alter_contato_email_alter_contato_mensagem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
